{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "162526d3_81e205ee",
        "filename": "cps-ncmp-service/src/main/java/org/onap/cps/ncmp/impl/inventory/sync/ModuleSyncService.java",
        "patchSetId": 1
      },
      "lineNbr": 122,
      "author": {
        "id": 7965
      },
      "writtenOn": "2025-01-27T13:05:44Z",
      "side": 0,
      "message": "we dont need this now ??",
      "revId": "0af1b07966f2c96af30497589fcb14ae5ea6d0d6",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d3900afc_071f5010",
        "filename": "cps-ncmp-service/src/main/java/org/onap/cps/ncmp/impl/inventory/sync/ModuleSyncService.java",
        "patchSetId": 1
      },
      "lineNbr": 122,
      "author": {
        "id": 6742
      },
      "writtenOn": "2025-01-27T13:59:44Z",
      "side": 0,
      "message": "No, there is a higher catch block in ModuleSyncTasks that also prints the exception. This is duplicate logging",
      "parentUuid": "162526d3_81e205ee",
      "revId": "0af1b07966f2c96af30497589fcb14ae5ea6d0d6",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a"
    }
  ]
}